# Generated by Django 3.1 on 2025-01-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_category_value',
            new_name='variation_value',
        ),
    ]
