# Generated by Django 3.1 on 2025-06-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line',
            new_name='address_line_1',
        ),
    ]
